export const RESET_ACTIONS = 'firestore:RESET_ACTIONS'

export const CREATE_USER_STARTED = 'firestore:CREATE_USER_STARTED'
export const CREATE_USER_FAILURE = 'firestore:CREATE_USER_FAILURE'
export const CREATE_USER_SUCCESS = 'firestore:CREATE_USER_SUCCESS'

export const EDIT_USER_STARTED = 'firestore:EDIT_USER_STARTED'
export const EDIT_USER_FAILURE = 'firestore:EDIT_USER_FAILURE'
export const EDIT_USER_SUCCESS = 'firestore:EDIT_USER_SUCCESS'

export const GET_USERS_STARTED = 'firestore:GET_USERS_STARTED'
export const GET_USERS_FAILURE = 'firestore:GET_USERS_FAILURE'
export const GET_USERS_SUCCESS = 'firestore:GET_USERS_SUCCESS'

export const FILTER_USERS_FETCH = 'firestore:FILTER_USERS_FETCH'
export const FILTER_USERS_COMPLETED = 'firestore:FILTER_USERS_COMPLETED'

export const CHANGE_ROLE_STARTED = 'firestore:CHANGE_ROLE_STARTED'
export const CHANGE_ROLE_FAILURE = 'firestore:CHANGE_ROLE_FAILURE'
export const CHANGE_ROLE_SUCCESS = 'firestore:CHANGE_ROLE_SUCCESS'

export const CREATE_CONTENT_STARTED = 'firestore:CREATE_CONTENT_STARTED'
export const CREATE_CONTENT_FAILURE = 'firestore:CREATE_CONTENT_FAILURE'
export const CREATE_CONTENT_SUCCESS = 'firestore:CREATE_CONTENT_SUCCESS'

export const EDIT_CONTENT_STARTED = 'firestore:EDIT_CONTENT_STARTED'
export const EDIT_CONTENT_FAILURE = 'firestore:EDIT_CONTENT_FAILURE'
export const EDIT_CONTENT_SUCCESS = 'firestore:EDIT_CONTENT_SUCCESS'

export const GET_CONTENTS_STARTED = 'firestore:GET_CONTENTS_STARTED'
export const GET_CONTENTS_FAILURE = 'firestore:GET_CONTENTS_FAILURE'
export const GET_CONTENTS_SUCCESS = 'firestore:GET_CONTENTS_SUCCESS'

export const FILTER_CONTENTS_FETCH = 'firestore:FILTER_CONTENTS_FETCH'
export const FILTER_CONTENTS_COMPLETED = 'firestore:FILTER_CONTENTS_COMPLETED'

export const DELETE_CONTENT_STARTED = 'firestore:DELETE_CONTENT_STARTED'
export const DELETE_CONTENT_FAILURE = 'firestore:DELETE_CONTENT_FAILURE'
export const DELETE_CONTENT_SUCCESS = 'firestore:DELETE_CONTENT_SUCCESS'